### ISSUE TITLE
Add article about dependency management

### ISSUE THREAD

**Issue by nacnudus** [ukgovdatascience/rap-website#3]
Discussion (packrat-focussed): https://github.com/ukgovdatascience/rap_companion/issues/86
More Discussion: https://github.com/ukgovdatascience/rap_companion/issues/89
Article in the RAP companion: https://ukgovdatascience.github.io/rap_companion/dep.html ([PR](https://github.com/ukgovdatascience/rap_companion/pull/97))

@matt-dray I think your RAP Companion chapter would be a good standalone article.  It's on the RAP website already as part of the companion, but I think it should be moved.  What do you think?

**Comment by nacnudus** [comment]
Also is enough of the [discussion](https://github.com/ukgovdatascience/rap_companion/issues/86) covered that it can be closed yet?

**Comment by matt-dray** [comment]
Yes, perhaps it should be a standalone article if the Companion is basically frozen. Perhaps the Companion should be rolled back to before this material was included? Or not, that seems like effort.

**Comment by nacnudus** [comment]
How about:
1. Leave it in the old-style companion
1. Remove the link from https://ukgovdatascience.github.io/rap-website/companion-index.html
1. Rename the file to `article-something-something.Rmd`
3. Link to it from https://ukgovdatascience.github.io/rap-website/articles.html

**Comment by matt-dray** [comment]
LInk is broken: https://ukgovdatascience.github.io/rap-website/article-dependency-and-reproducibility.Rmd.html

Possibly because of `.Rmd.html` rather than `.html`?

**Comment by nacnudus** [comment]
:link: :man_facepalming:
