### ISSUE TITLE
Set up Travis builds

### ISSUE THREAD

**Issue by nacnudus** [ukgovdatascience/rap-website#7]
Build on push to master?

Examples:
* https://github.com/adamrobinson361/r-workflow/blob/master/.travis.yml
* https://github.com/departmentfortransport/ds-r-training

Also write a how-to article.

**Comment by tjtnew** [comment]
This may (or may not) be worth investigating https://github.com/ropenscilabs/tic

**Comment by nacnudus** [comment]
Implemented by 45696f7dbbc230f83e413d426380cf03ef3aea1b and https://github.com/ukgovdatascience/rap-website/pull/10.  Thanks @tjtnew!
